export const LIGHT_COLORS = {
  PRIMARY: '#BFE3CC',
  SECONDARY: '#BBDDE1',
  TERTIARY: '#030318',
  QUATERNARY: '#FAFAFA',
  BACKGROUND: '#FFFFFF',
  HINT: '#828282',
  LIGHT_HINT: '#EAEAEA',
  NEGATIVE: '#DB6363',
  POSITIVE: '#90D37A',
};
