export const BORDER_RADIUS = {
  BUTTON: 20,
  INPUT: 20,
  BOTTOM_SHEET: 25,
  PROFILE_BAR: 40,
};

export const BOTTOM_SHEET_HEIGHT = {
  PICTURE_SELECTION: 580,
  LANGUAGE_SELECTION: 560,
  THEME_SELECTION: 560,
};

export const ACTIVE_OPACITY = {
  HIGH: 0.7,
  MEDIUM: 0.5,
  LOW: 0.3,
};

export const STROKE_WIDTH = {
  MEDIUM: 1.5,
  BOLD: 3,
};
