export const BORDER_RADIUS = {
  SKELETON_4: 4,
  SKELETON_5: 5,
  SKELETON_15: 15,
  BUTTON: 20,
  INPUT: 20,
  BOTTOM_SHEET: 25,
  PROFILE_BAR: 40,
  CIRCLE: 100,
};

export const APP = {
  NAME: 'TradeMood',
  VERSION: 'v1.1.5',
};

export const BOTTOM_SHEET_HEIGHT = {
  PICTURE_SELECTION: 580,
  LANGUAGE_SELECTION: 520,
  THEME_SELECTION: 520,
  DELETE_POST: 600,
};

export const ACTIVE_OPACITY = {
  HIGH: 0.7,
  MEDIUM: 0.5,
  LOW: 0.3,
};

export const STROKE_WIDTH = {
  MEDIUM: 1.5,
  HIGH: 2,
  BOLD: 3,
};

export const ICON_SIZE = {
  SMALL_ICON: 25,
  ICON: 30,
  ICON_MEDIUM: 35,
  ACTIVITY_INDICATOR: 40,
  PROGRESS_BAR_HEIGHT: 40,
  POST_IMAGE: 40,
  GO_BACK: 42,
  BIG_ICON: 48,
  PROFILE_IMAGE: 80,
  IMAGE_PICKER_BUTTON: 80,
  PROFILE_WALL_PHOTO: 130,
  IMAGE_PICKER_MEDIUM: 200,
  IMAGE_PICKER_BIG: 250,
};
